#pragma once

#define __DEVICE_NAME__ "CandyCrane"
#define __DEVICE_VERSION__ "0.1"


/* NETWORK */
/*
#define NETWORK_WAIT_TIME_PER_TRY 10 //seconds
#define NETWORK_TRY_TIMES 3

#define WIFI_PREFERENCES_FILENAME "wifi"
#define WIFI_PREFERENCES_SSID_KEY "ssid"
#define WIFI_PREFERENCES_PASWORD_KEY "password"
#define MQTT_BROKER_PREFERENCES_FILENAME "mqtt"
#define MQTT_BROKER_PREFERENCES_ADDRESS "mqttAddress"
*/

/* CORE and PRIORITY Assignments */
#define STACK_SIZE (ESP_TASK_MAIN_STACK) // Stack size for each new thread

//#define WEB_SERVER_PRIORITY tskIDLE_PRIORITY+1
//#define OTA_PRIORITY tskIDLE_PRIORITY+1
#define CRANE_CONTROL_PRIORITY tskIDLE_PRIORITY+1
#define CRANE_CONTROL_QUEUE_HANDLER_PRIORITY tskIDLE_PRIORITY+1

//#define WEBSERVER_CORE	0
//#define OTA_CORE	0
#define CRANE_CONTROL_CORE 1
#define CRANE_CONTROL_QUEUE_HANDLER_CORE 0

/* Crane Controller */
#define BUCKET_HEARTBEAT_INTERVAL 500
#define BUCKET_LOST_PONG_COUNT 120
#define BUCKET_HEARBEATS_MAX_MISSED 1

#define BUCKET_NO_DISTANCE -1
#define BUCKET_COMMAND_WAIT_TIME 5000
#define BUCKET_MOVE_WAIT_TIME 10000