#pragma once

#define __DEVICE_NAME__ "CCBucket"
#define __DEVICE_VERSION__ "0.1"

#define SERVO1_PIN 3

#define DEFAULT_BUCKET_OPEN_ANGLE 70
#define DEFAULT_BUCKET_OPEN_SPEED 80

/*
#define EEPROM_BUCKET_OPEN_ANGLE 0
#define EEPROM_BUCKET_OPEN_ANGLE_LENGTH (sizeof(int))

#define EEPROM_BUCKET_CLOSE_ANGLE (EEPROM_BUCKET_OPEN_ANGLE + EEPROM_BUCKET_OPEN_ANGLE_LENGTH)
#define EEPROM_BUCKET_CLOSE_ANGLE_LENGTH (sizeof(int))

#define EEPROM_BUCKET_OPEN_SPEED (EEPROM_BUCKET_CLOSE_ANGLE + EEPROM_BUCKET_CLOSE_ANGLE_LENGTH)
#define EEPROM_BUCKET_OPEN_SPEED_LENGTH (sizeof(int))

#define EEPROM_BUCKET_CLOSE_SPEED (EEPROM_BUCKET_OPEN_SPEED + EEPROM_BUCKET_OPEN_SPEED_LENGTH)
#define EEPROM_BUCKET_CLOSE_SPEED_LENGTH (sizeof(int))
*/